/*
 Nathan Buth
 3-22-2012
 Project 4
 MIU 1203
*/

var json = {
    "character1": {
        "level": ["Level:", "30"],
        "role": ["Role:", "Striker"],
        "characterClass": ["Class:", "Sorceror"],
        "race": ["Race:", "Halfling"],
        "characterName": ["Character Name:", "Baltha"],
        "gender": ["Gender:", "Female"],
		"height": ["Height:", "4 feet & 6 inches"],
		"weight": ["Weight:", "100 pounds"],
		"age": ["Age:", "62"],
		"alignment": ["Alignment:", "Neutral"],
		"deity": ["Deity:", "Corellon"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:","Sly and mysterious." ],
		"personalityTraits": ["Personality Traits:", "Mischeivous but kind."],
    },
	"character2": {
        "level": ["Level:", "25"],
        "role": ["Role:", "Defender"],
        "characterClass": ["Class:", "Swordmage"],
        "race": ["Race:", "Bladeling"],
        "characterName": ["Character Name:", "Malikai"],
        "gender": ["Gender:", "Male"],
		"height": ["Height:", "6 feet"],
		"weight": ["Weight:", "190 pounds"],
		"age": ["Age:", "100"],
		"alignment": ["Alignment:", "Good"],
		"deity": ["Deity:", "Sune"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Dark, a loner."],
		"personalityTraits": ["Personality Traits:", "A strong believer in good but due to his past he is not trustful."],
    },
	"character3": {
        "level": ["Level:", "20"],
        "role": ["Role:", "Controller"],
        "characterClass": ["Class:", "Invoker"],
        "race": ["Race:", "Satyr"],
        "characterName": ["Character Name:", "Vylox"],
        "gender": ["Gender:", "Male"],
		"height": ["Height:", "7 feet & 5 inches"],
		"weight": ["Weight:", "237 pounds"],
		"age": ["Age:", "463 years old"],
		"alignment": ["Alignment:", "Chaotic Evil"],
		"deity": ["Deity:", "Tharizdun"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Imposing but seemingly kind."],
		"personalityTraits": ["Personality Traits:", "He is extremely charismatic so often brings those around him as well as strangers into trouble."],
    },
	"character4": {
        "level": ["Level:", "15"],
        "role": ["Role:", "Leader"],
        "characterClass": ["Class:", "Artificer"],
        "race": ["Race:", "Genasi"],
        "characterName": ["Character Name:", "Flamora"],
        "gender": ["Gender:", "Female"],
		"height": ["Height:", "5 feet & 7 inches"],
		"weight": ["Weight:", "136 pounds"],
		"age": ["Age:", "27"],
		"alignment": ["Alignment:", "Chaotic Neutral"],
		"deity": ["Deity:", "Erathis"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Tall and lean, she always looks like she is about to do something rash."],
		"personalityTraits": ["Personality Traits:", "Hot-headed and completely unpredictable."],
    },
	"character5": {
        "level": ["Level:", "10"],
        "role": ["Role:", "Striker"],
        "characterClass": ["Class:", "Warlock"],
        "race": ["Race:", "Githzerai"],
        "characterName": ["Character Name:", "Folruin"],
        "gender": ["Gender:", "Other"],
		"height": ["Height:", "6 feet & 3 inches"],
		"weight": ["Weight:", "240 pounds"],
		"age": ["Age:", "72"],
		"alignment": ["Alignment:", "Neutral"],
		"deity": ["Deity:", "Aurom"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Dark and shady"],
		"personalityTraits": ["Personality Traits:", "Although neutral he seems to be darker.  Very mysterious to the point of not many people have seen his face."],
    },
	"character6": {
        "level": ["Level:", "5"],
        "role": ["Role:", "Defender"],
        "characterClass": ["Class:", "Paladin"],
        "race": ["Race:", "Kalashtar"],
        "characterName": ["Character Name:", "Jalah"],
        "gender": ["Gender:", "Female"],
		"height": ["Height:", "5 feet & 11 inches"],
		"weight": ["Weight:", "154 pounds"],
		"age": ["Age:", "34"],
		"alignment": ["Alignment:", "Lawful Good"],
		"deity": ["Deity:", "The Path of Light"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Tall and very direct."],
		"personalityTraits": ["Personality Traits:", "She would do anything for the good of the people around her.  Often she is overly bold though"],
    },
	"character7": {
        "level": ["Level:", "1"],
        "role": ["Role:", "Controller"],
        "characterClass": ["Class:", "Druid"],
        "race": ["Race:", "Razorclaw Shifter"],
        "characterName": ["Character Name:", "Maran"],
        "gender": ["Gender:", "Other"],
		"height": ["Height:", "7 feet"],
		"weight": ["Weight:", "227 pounds"],
		"age": ["Age:", "21"],
		"alignment": ["Alignment:", "Chaotic Good"],
		"deity": ["Deity:", "Mielikki"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Very ragged and almost crazy looking"],
		"personalityTraits": ["Personality Traits:", "Very frantic.  Good but can be extremely cruel to anybody trying to hurt their forest."],
    },
	"character8": {
        "level": ["Level:", "3"],
        "role": ["Role:", "Leader"],
        "characterClass": ["Class:", "Bard"],
        "race": ["Race:", "Tiefling"],
        "characterName": ["Character Name:", "Tusler"],
        "gender": ["Gender:", "Female"],
		"height": ["Height:", "3 feet & 7 inches"],
		"weight": ["Weight:", "85 pounds"],
		"age": ["Age:", "43"],
		"alignment": ["Alignment:", "Good"],
		"deity": ["Deity:", "Olladra"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Short but feisty"],
		"personalityTraits": ["Personality Traits:", "Is unstoppable in her quest to become a recognized Master Bard she is very persistent but a fantastic listener."],
    },
	"character9": {
        "level": ["Level:", "6"],
        "role": ["Role:", "Striker"],
        "characterClass": ["Class:", "Avenger"],
        "race": ["Race:", "Half-Elf"],
        "characterName": ["Character Name:", "Torlock"],
        "gender": ["Gender:", "Male"],
		"height": ["Height:", "5 feet & 7 inches"],
		"weight": ["Weight:", "135 pounds"],
		"age": ["Age:", "25"],
		"alignment": ["Alignment:", "Lawful Good"],
		"deity": ["Deity:", "The Silver Flame"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Strong and forceful."],
		"personalityTraits": ["Personality Traits:", "Mistrusting and rash due to his young age."],
    },
	"character10": {
        "level": ["Level:", "9"],
        "role": ["Role:", "Defender"],
        "characterClass": ["Class:", "Warden"],
        "race": ["Race:", "Dwarf"],
        "characterName": ["Character Name:", "Balathorn"],
        "gender": ["Gender:", "Female"],
		"height": ["Height:", "4 feet & 6 inches"],
		"weight": ["Weight:", "170 pounds"],
		"age": ["Age:", "54"],
		"alignment": ["Alignment:", "Lawful Good"],
		"deity": ["Deity:", "Clangeddin Silverbeard"],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", "Tall for a dwarf and quite raunchy."],
		"personalityTraits": ["Personality Traits:", "Very flirtatious but in a teasing manner.  She would do anything for her friends and the good of the world."],
    },
	"character11": {
        "level": ["Level:", "12"],
        "role": ["Role:", "Controller"],
        "characterClass": ["Class:", "Seeker"],
        "race": ["Race:", "Revenant"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character12": {
        "level": ["Level:", "15"],
        "role": ["Role:", "Leader"],
        "characterClass": ["Class:", "Runepriest"],
        "race": ["Race:", "Warforged"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character13": {
        "level": ["Level:", "18"],
        "role": ["Role:", "Striker"],
        "characterClass": ["Class:", "Ranger"],
        "race": ["Race:", "Drow"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character14": {
        "level": ["Level:", "21"],
        "role": ["Role:", "Defender"],
        "characterClass": ["Class:", "Battlemind"],
        "race": ["Race:", "Minotaur"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character15": {
        "level": ["Level:", "24"],
        "role": ["Role:", "Controller"],
        "characterClass": ["Class:", "Psion"],
        "race": ["Race:", "Shardmind"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character16": {
        "level": ["Level:", "27"],
        "role": ["Role:", "Leader"],
        "characterClass": ["Class:", "Ardent"],
        "race": ["Race:", "Goliath"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character17": {
        "level": ["Level:", "30"],
        "role": ["Role:", "Striker"],
        "characterClass": ["Class:", "Assassin"],
        "race": ["Race:", "Dragonborn"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character18": {
        "level": ["Level:", "11"],
        "role": ["Role:", "Defender"],
        "characterClass": ["Class:", "Fighter(Knight)"],
        "race": ["Race:", "Human"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character19": {
        "level": ["Level:", "22"],
        "role": ["Role:", "Controller"],
        "characterClass": ["Class:", "Wizard(Arcanist)"],
        "race": ["Race:", "Elf"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
	"character20": {
        "level": ["Level:", "8"],
        "role": ["Role:", "Leader"],
        "characterClass": ["Class:", "Shaman"],
        "race": ["Race:", "Eladrin"],
        "characterName": ["Character Name:", ""],
        "gender": ["Gender:", ""],
		"height": ["Height:", ""],
		"weight": ["Weight:", ""],
		"age": ["Age:", ""],
		"alignment": ["Alignment:", ""],
		"deity": ["Deity:", ""],
		"mannerismsAndAppearance": ["Mannerism and Appearance:", ""],
		"personalityTraits": ["Personality Traits:", ""],
    },
};